name: Build Autoware container images
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - autoware.repos.yml
      - .github/workflows/arm64.yml # Self-trigger 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bounverif/autoware
  AUTOWARE_VERSION: 20240613

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  autoware-container-build:
    runs-on: macos-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: '/var/lib/docker'

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Builder image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: autoware-builder
          build-args: |
            "AUTOWARE_VERSION=${{ env.AUTOWARE_VERSION }}"
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.AUTOWARE_VERSION }}-builder
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Builder w/cache image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: autoware-builder-with-cache
          build-args: |
            "AUTOWARE_VERSION=${{ env.AUTOWARE_VERSION }}"
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.AUTOWARE_VERSION }}-builder-with-cache
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
