name: buildah-build-devel
on:
  workflow_dispatch:
  schedule:
    - cron: "41 19 * * *" # 19:41 UTC everyday
  push:
    paths:
      - .github/workflows/buildah-build-devel.yml # Self-trigger
      - containers/autoware-devel/**

env:
  REGISTRY: ghcr.io/bounverif
  IMAGE_NAME: autoware
  AUTOWARE_VERSION: latest
  CONTAINERS_ROOT: /home/runner/.local/share/containers
  TMPDIR: /home/runner/.local/share/containers/tmp

permissions:
  contents: read
  packages: write

jobs:
  buildah-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true
      
    steps:
      - name: Install container tools
        run: sudo apt-get install podman buildah jq
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 2048 # Reserve disk space for repository
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          build-mount-path: ${{ env.CONTAINERS_ROOT }} # The remaining space only for container build

      - run: mkdir -p $TMPDIR

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare environment variables
        run: |
          echo "HOSTARCH=$(podman info --format='{{.Host.Arch}}')" >> $GITHUB_ENV
          echo "PLATFORM=$(podman info --format='{{.Version.OsArch}}' | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "AUTOWARE_VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create VERSION file for the container
        run: |
          mkdir -p containers/etc/autoware
          echo ${{ env.AUTOWARE_VERSION }} > containers/etc/autoware/VERSION

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base container image
        id: build-base
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.AUTOWARE_VERSION }}-base
            ${{ env.AUTOWARE_VERSION }}-base-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            AUTOWARE_VERSION=${{ env.AUTOWARE_VERSION }}
          extra-args: |
            --target autoware-base
          containerfiles: |
            containers/autoware-devel/Dockerfile
          context: containers

      - name: Build builder container image
        id: build-builder
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.AUTOWARE_VERSION }}-builder
            ${{ env.AUTOWARE_VERSION }}-builder-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            AUTOWARE_VERSION=${{ env.AUTOWARE_VERSION }}
          extra-args: |
            --target autoware-builder
          containerfiles: |
            containers/autoware-devel/Dockerfile
          context: containers

      - name: Build builder-with-cache container image
        id: build-builder-with-cache
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.AUTOWARE_VERSION }}-builder-with-cache
            ${{ env.AUTOWARE_VERSION }}-builder-with-cache-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            AUTOWARE_VERSION=${{ env.AUTOWARE_VERSION }}
          extra-args: |
            --target autoware-builder-with-cache
          containerfiles: |
            containers/autoware-devel/Dockerfile
          context: containers

      - name: Build devel container image
        id: build-devel
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.AUTOWARE_VERSION }}-devel
            ${{ env.AUTOWARE_VERSION }}-devel-${{ env.HOSTARCH }}
          layers: true
          oci: true
          build-args: |
            AUTOWARE_VERSION=${{ env.AUTOWARE_VERSION }}
          extra-args: |
            --target autoware-devel
          containerfiles: |
            containers/autoware-devel/Dockerfile
          context: containers

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-base-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-base.outputs.image }}
          tags: ${{ env.AUTOWARE_VERSION }}-base-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-autoware-base-${{ env.AUTOWARE_VERSION }}-${{ env.PLATFORM }}

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-builder-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-builder.outputs.image }}
          tags: ${{ env.AUTOWARE_VERSION }}-builder-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-autoware-builder-${{ env.AUTOWARE_VERSION }}-${{ env.PLATFORM }}

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-builder-with-cache-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-builder-with-cache.outputs.image }}
          tags: ${{ env.AUTOWARE_VERSION }}-builder-with-cache-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-autoware-bwithcache-${{ env.AUTOWARE_VERSION }}-${{ env.PLATFORM }}

      - name: Push to GitHub Container Repository
        if: github.ref == 'refs/heads/main'
        id: push-devel-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build-devel.outputs.image }}
          tags: ${{ env.AUTOWARE_VERSION }}-devel-${{ env.HOSTARCH }}
          digestfile: ${{ runner.temp }}/digest-autoware-devel-${{ env.AUTOWARE_VERSION }}-${{ env.PLATFORM }}

      - name: Upload digests
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: digest-autoware-${{ env.AUTOWARE_VERSION }}-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digest-*
          if-no-files-found: error
          retention-days: 1
          compression-level: 0 # no compression

  buildah-merge:
    name: Merge container images
    runs-on: ubuntu-24.04
    needs: buildah-build
    if: github.ref == 'refs/heads/main' && always()
    steps:
      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-*
          merge-multiple: true

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment variables
        run: |
          echo "AUTOWARE_VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create and push manifest list for autoware-base
        run: |
          MANIFEST=autoware-base
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-autoware-base-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.AUTOWARE_VERSION }}-base
          if [ "${{ env.AUTOWARE_VERSION }}" == "${{ env.CURRENT_DATE }}" ]; then
            buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-base 
          fi
          
      - name: Create and push manifest list for autoware-builder
        run: |
          MANIFEST=autoware-builder
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-autoware-builder-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.AUTOWARE_VERSION }}-builder
          if [ "${{ env.AUTOWARE_VERSION }}" == "${{ env.CURRENT_DATE }}" ]; then
            buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-builder 
          fi

      - name: Create and push manifest list for autoware-builder-with-cache
        run: |
          MANIFEST=autoware-bwithcache
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-autoware-bwithcache-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.AUTOWARE_VERSION }}-builder-with-cache
          if [ "${{ env.AUTOWARE_VERSION }}" == "${{ env.CURRENT_DATE }}" ]; then
            buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-builder-with-cache
          fi

      - name: Create and push manifest list for autoware-devel
        run: |
          MANIFEST=autoware-devel
          FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          buildah manifest create $MANIFEST
          for digest in ${{ runner.temp }}/digests/digest-autoware-devel-*; do
            echo "Adding $(cat $digest)"
            buildah manifest add $MANIFEST $FULL_IMAGE_NAME@$(cat $digest)
          done
          buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:${{ env.AUTOWARE_VERSION }}-devel
          if [ "${{ env.AUTOWARE_VERSION }}" == "${{ env.CURRENT_DATE }}" ]; then
            buildah manifest push --all $MANIFEST docker://$FULL_IMAGE_NAME:latest-devel 
          fi

  test-builder-with-cache:
    if: github.ref == 'refs/heads/main'
    needs: buildah-merge
    uses: ./.github/workflows/test-builder-with-cache.yml
