name: test-builder-with-cache

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - .github/workflows/test-builder-with-cache.yml # Self-trigger

jobs:
  build-package-with-cache:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bounverif/autoware:latest-builder-with-cache

    strategy:
      fail-fast: false
      matrix:
        package:
          - autoware_tensorrt_yolox
          - autoware_launch

    steps:
      - name: Checkout Autoware repository
        uses: actions/checkout@v4
        with:
          repository: 'autowarefoundation/autoware'

      - name: Build up to ${{ matrix.package }}
        run: |
          mkdir -p src
          export CCACHE_BASEDIR=${PWD}
          export CCACHE_READONLY=1
          ccache --show-config
          vcs import src --shallow --input autoware.repos
          . /opt/ros/humble/setup.sh
          ccache --zero-stats
          colcon build --packages-up-to ${{ matrix.package }}
          ccache -v --show-stats
